### ISSUE TITLE
Doesn't support Arduino 1.5.x

### ISSUE THREAD

**Issue by thinkyhead** [unrepentantgeek/brainwave-arduino#2]
I would love to see this support added. I've been trying to get it to work, but no luck so far, as documentation on the changes from the old scheme is spotty. If I do manage to get it working I'll fork and send a pull request.

**Comment by ex-nerd** [comment]
See pull request #3.  This seems to work, though I'm having unrelated compile issues with Marlin itself so I can't test thoroughly.

**Comment by thinkyhead** [comment]
:bow:

**Comment by ex-nerd** [comment]
Wow, talk about delayed PR responses. 😮
